### ISSUE TITLE
patch of local-configure.patch does not work

### ISSUE THREAD

**Issue by liwenjie119** [Zackptg5/curl-boringssl-android#1]
When I complate the curl, it is something wrong with it:

configure: error: BROTLI libs and/or directories were not found where specified!
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Index: curl/lib/curl_config.h
|===================================================================
|--- curl.orig/lib/curl_config.h
|+++ curl/lib/curl_config.h
--------------------------
File to patch:

I can not find curl/lib/curl_config.h in ./curl ,and I set export STATIC=true in build.sh, but I think it probably do not work.

**Comment by Zackptg5** [comment]
Did you clone with the `--recurse-submodules` arg as in the readme? I'm in the process of updating curl now and it runs fine for me. I'm on Manjaro btw, I haven't had nearly as much luck with ubuntu
