### ISSUE TITLE
curl-arm only works with dns-servers switch

### ISSUE THREAD

**Issue by Baltazar500** [Zackptg5/curl-boringssl-android#2]
`curl-arm -sv 'http://google.ru'`
`* Could not resolve: google.ru (Could not contact DNS servers)`
`* Closing connection 0`

***

`curl-arm -sv --dns-servers 8.8.8.8 'http://google.ru'`
`<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">`
`<TITLE>301 Moved</TITLE></HEAD><BODY>`
`<H1>301 Moved</H1>`
`The document has moved`
`<A HREF="http://www.google.ru/">here</A>.`
`</BODY></HTML>`

**Comment by Baltazar500** [comment]
>Possibly.

OK, I attached the log to the post [strace_curl-arm.zip](https://github.com/Zackptg5/curl-boringssl-android/files/5215853/strace_curl-arm.zip)

>I'm wondering though, can you try the more basic curl with openssl here:
https://github.com/robertying/openssl-curl-android

armv7 curl 7.70.0 crashed at startup

>bash-4.4# curl-robertying -sikvL 'http://google.com'
>soinfo_relocate(linker.cpp:992): cannot locate symbol "tcgetattr" referenced by "curl-robertying"...CANNOT LINK EXECUTABLE

**Comment by Zackptg5** [comment]
Hmm, not sure what to make of the strace for this binary, I've looked at strace logs for this before and wasn't sure where the problem lied

As for the robert one, did you build them with the scripts or use the release versions? The build script by default has minapi of 21 (lollipop - 5.0) and is dynamically linked which would explain the errors for you

**Comment by Zackptg5** [comment]
[build.zip](https://github.com/Zackptg5/curl-boringssl-android/files/5235930/build.zip)
Compiled this with robert's build script using minapi of 17, see if it works for you

**Comment by Baltazar500** [comment]
>As for the robert one, did you build them with the scripts or use the release versions?

I used the release version. I don't have enough experience to build binaries :(

>build.zip Compiled this with robert's build script using minapi of 17, see if it works for you

Yes. It worked. Works without the "-k" switch :) Works without dns resolving switch :)

**Comment by Zackptg5** [comment]
Ok, if you could close the issue at roberts repo since the release binaries were for lollipop+, my guess for why mine isn't working is due to it using boringssl rather than openssl. Looks like google switched to boringssl in marshmallow so maybe older versions require openssl. What's the content of you /system/etc/security folder? Do you have a cacerts folder with a bunch of .0 files in it or something else?

**Comment by Zackptg5** [comment]
[curl.zip](https://github.com/Zackptg5/curl-boringssl-android/files/5240070/curl.zip)
I compiled these with my script but using openssl (and minapi of 17). Can you see if either one works? The dynamic one requires the placement of the libs in the folder

**Comment by Baltazar500** [comment]
>Ok, if you could close the issue at roberts repo since the release binaries were for lollipop+

OK, I closed the issue.

>my guess for why mine isn't working is due to it using boringssl rather than openssl. Looks like google switched to boringssl in marshmallow so maybe older versions require openssl. What's the content of you /system/etc/security folder? Do you have a cacerts folder with a bunch of .0 files in it or something else?

Yes, in the cacerts "/system/etc/security/cacerts" directory. The original certificates are out of date. A month earlier, I extract the certificates from https://android.googlesource.com/platform/system/ca-certificates/+/master/files/ and replaced them.

>curl.zip I compiled these with my script but using openssl (and minapi of 17). Can you see if either one works? The dynamic one requires the placement of the libs in the folder

I used static build. Same problem.

>bash-4.4# curl-Zackptg5-4.2.2 -svikL 'http://www.google.com'
>* Could not resolve: www.google.com (Could not contact DNS servers)
>* Closing connection 0
>bash-4.4#

Works only with the "--dns-servers x.x.x.x" switch

**Comment by Zackptg5** [comment]
Does the dynamic one work? as root? With aria2, static one has similar problem but dynamic is fine

**Comment by Baltazar500** [comment]
>Does the dynamic one work?

Now I have checked dynamic build and it works. I use static builds if possible. dynamic ones require unset/set PATH/LD_LIBRARY_PATH (there are library conflicts of other utilities)

>as root? 

yes

>With aria2, static one has similar problem but dynamic is fine

Is there a problem with static builds ? Is it possible to solve it ?

**Comment by Zackptg5** [comment]
> Is there a problem with static builds ? Is it possible to solve it ?

With aria2, name resolution fails for static builds only. However this can be remedied by passing the `--async-dns` flag to it. Other than that, it behaves like curl where you have to run it as root or it won't resolve dns

Static build I posted worked fine for me using the command you did when run as root so I'm not sure what else it would be at this point. Only thing I could think of would be one of the extra dependencies in mine (maybe c-ares). If the one by roberts works for you though I'd just stick with it (or try aria2 and osm0sis' busybox - wget applet)

**Comment by Baltazar500** [comment]
>or try aria2 and osm0sis' busybox - wget applet

Where can I get the required aria2 release ?

I downloaded busybox from osm0sis here https://github.com/Magisk-Modules-Repo/busybox-ndk/blob/master/busybox-arm

>bash-4.4# busybox-arm-osm0sis --help|head -n1
>BusyBox v1.31.1-osm0sis (2019-11-01 15:06:32 ADT) multi-call binary.

wget works :)

**Comment by Zackptg5** [comment]
I recently added it to my cross compiled binaries repo. Dynamic won't work for you due to api but static should in theory

**Comment by Baltazar500** [comment]
>I recently added it to my cross compiled binaries repo. Dynamic won't work for you due to api but static should in theory

OK. I downloaded aria2 from repo :)

With the ca-bundle.crt certificate

>bash-4.4# aria2c.bin-arm --ca-certificate=/data/tools/bin/ssl/certs/ca-bundle.crt --async-dns 'https://google.com'
>
>__bionic_open_tzdata: couldn't find any tzdata when looking for UTC-10!
>__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
>09/20 15:54:57 [NOTICE] Downloading 1 item(s)
>
>09/20 15:54:58 [ERROR] CUID#7 - Download aborted. URI=https://google.com
>Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://google.com
>  -> [AbstractCommand.cc:792] errorCode=19 CUID#7 - Name resolution for google.com failed:Could not contact DNS servers
>
>09/20 15:54:58 [NOTICE] Download GID#e72a06476e3f5223 not complete: 
>
>Download Results:
>gid   |stat|avg speed  |path/URI
>======+====+===========+=======================================================
>e72a06|[ERR |       0B/s|https://google.com
>
>Status Legend:
>(ERR):error occurred.
>
>aria2 will resume download if the transfer is restarted.
>If there are any errors, then see the log file. See '-l' option in help/man page for details.

Without ca-bundle.crt certificate

>bash-4.4# aria2c.bin-arm --check-certificate=false --async-dns 'https://google.com'
>
>__bionic_open_tzdata: couldn't find any tzdata when looking for UTC-10!
>__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
>09/20 15:55:11 [NOTICE] Downloading 1 item(s)
>
>09/20 15:55:11 [ERROR] Failed to load trusted CA certificates from /system/etc/security/ca-certificates.crt. Cause: error:02001002:system library:fopen:No such file or directory
>
>09/20 15:55:12 [ERROR] CUID#7 - Download aborted. URI=https://google.com
>Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://google.com
>  -> [AbstractCommand.cc:792] errorCode=19 CUID#7 - Name resolution for google.com failed:Could not contact DNS servers
>
>09/20 15:55:12 [NOTICE] Download GID#00c92cc0ce1b6e1a not complete: 
>
>Download Results:
>gid   |stat|avg speed  |path/URI
>======+====+===========+=======================================================
>00c92c|[ERR |       0B/s|https://google.com
>
>Status Legend:
>(ERR):error occurred.
>
>aria2 will resume download if the transfer is restarted.
>If there are any errors, then see the log file. See '-l' option in help/man page for details.

Without "async-dns" switch

>bash-4.4# aria2c.bin-arm --check-certificate=false 'https://google.com'
>
>__bionic_open_tzdata: couldn't find any tzdata when looking for UTC-10!
>__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
>09/20 16:06:20 [NOTICE] Downloading 1 item(s)
>
>09/20 16:06:20 [ERROR] Failed to load trusted CA certificates from /system/etc/security/ca-certificates.crt. Cause: error:02001002:system library:fopen:No such file or directory
>
>09/20 16:06:20 [ERROR] CUID#7 - Download aborted. URI=https://google.com
>Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://google.com
>  -> [NameResolver.cc:60] errorCode=19 Failed to resolve the hostname google.com, cause: No address associated with hostname
>
>09/20 16:06:20 [NOTICE] Download GID#3a12bd0b1b149014 not complete: 
>
>Download Results:
>gid   |stat|avg speed  |path/URI
>======+====+===========+=======================================================
>3a12bd|[ERR |        n/a|https://google.com
>
>Status Legend:
>(ERR):error occurred.
>
>aria2 will resume download if the transfer is restarted.
>If there are any errors, then see the log file. See '-l' option in help/man page for details.

wget

>bash-4.4# ls -lanh \`which wget\`
>lrwxrwxrwx    1 0        0             36 Sep 20 15:40 /data/sdext1/bin/wget -> /data/sdext1/bin/busybox-arm-osm0sis

I only tested static build

**Comment by Zackptg5** [comment]
Hmmm, so it's behaving like curl then which is strange because I use openssl in aria2. I'd just stick with busybox's wget then since it works for you. Sorry!

**Comment by Zackptg5** [comment]
I won't be able to fix this since I don't have an old enough device to test this on :(
